lib/git-log.js, package.json, tests/git-log.spec.js, tests/utils.js, tests/versionist.spec.js
There are some commits we've seen in the wild while using this module that
indent the body for some reason (a space or two spaces usually). For
example:
```
My commit
Lorem ipsum dolor sit amet.
Hello world.
Fixes: #350
```
This confuses the YAML parser, since applying our custom `git log
--pretty` format to such commits yields:
```
- subject >-
My commit
body: |-
Lorem ipsum dolor sit amet.
Hello world.
Fixes: #350
```
Which of course is not well indented.
We've considered moving away from YAML to another serialisation technology
that copes with these kind of multi-line string issues, however we found a
small workaround that allows us to not spend time building and maintaing
something else:
If we pass *any* dummy string as the first line of `body`, and make it well
indented, the …
=> fix: parse commits with indented body

lib/git-log.js, lib/versionist.js, tests/git-log.spec.js, tests/utils.js, tests/versionist.spec.js
`child_process.exec` imposes a limit on the largest amount of data allowed
on `stdout` or `stderr` (200 * 1024 bytes by default, according to the
documentation).
Since this limit can be easily reached when runnign Versionist on huge
projects, instead of executing the `git log` command, we spawn it, and
colelct the `stdout` output as it comes.
Changelog-Entry: Fix `stdout maxBuffer exceeded` when parsing big logs.
=> fix: `stdout maxBuffer exceeded` when parsing big logs 

.gitignore, versionist.conf.js
We use a `versionist.conf.js` in Versionist's repo itself for
demonstration purposes.
=> chore: add versionist.conf.js

bin/cli.js
This means the `template` option is no longer required, and users can
get something to display in their terminals with really minimum
configuration.
Changelog-Entry: Add a simple default template.
=> feat: add simple default template

README.md
See: https://github.com/resin-io/versionist/pull/4
=> docs: template option is no longer required

README.md
Instead of simply showing how to run Versionist, we now provide detailed
instructions to clone the Versionist repository as an example, and run
Versionist on it for real, in order to get a better feel of what
Versionist is capable of.
=> docs: add a full reproducible example to README

lib/semver.js, lib/versionist.js, tests/semver.spec.js, tests/versionist.spec.js
We were currently blindly passing the version the user sets as the
`--current` option to the Handlebars template, without imposing any
validation or normalisation.
This would cause problems with invalid semver versions, or if the user
sometimes passes a version preppended with a `v` and sometimes not,
since the data passed to the template would not always be consistent.
This PR introduces a function called `semver.normalize()`, which returns
the normalised version, or throws if the version is not valid.
Changelog-Entry: Normalize `--current` version before passing it to the template.
=> fix: normalize template version

README.md, bin/cli.js, lib/presets.js, package.json, tests/presets.spec.js
This hooks is used to determine how the CHANGELOG generated by Versionist
is added to the project's CHANGELOG file.
It ships with a `prepend` preset, which as the name implies, simply
prepends the entry to the CHANGELOG file specified with `changelogFile`,
which uses as a default value..
Changelog-Entry: Add `addEntryToChangelog` option hook.
=> feat: add `addEntryToChangelog` option hook

.eslintrc.yml
We're currently forcing a UNIX linebreak style, which causes hundreds of
complaints from the linter when cloning the project in a Windows machine
with a default configuration.
=> chore: don't force a linebreak style in ESLint

bin/cli.js
There is a bug in the way we apply default values for boolean options.
If the user explicitly sets an option to `false`, then `property ||
default` will incorrectly be evaluated to `default`, which might be
`true.
Changelog-Entry: Don't apply default values on boolean options explicitly set to `false`.
=> fix: apply default values if the current value is not defined

README.md, bin/cli.js, lib/markdown.js, lib/presets.js, package.json, tests/markdown.spec.js, tests/presets.spec.js
Currently, a generated entry is blindly added to the `CHANGELOG` file. This
means that if a user runs the same command over and over again, the same
duplicated entry will be added to the `CHANGELOG` multiple times.
This commit makes use of `getChangelogDocumentedVersions` to determine
whether the calculated version should be added to the CHANGELOG or not.
Changelog-Entry: Make CHANGELOG entry addition idempotent.
=> feat: make changelog entry addition idempotent

README.md, bin/cli.js, lib/presets.js, lib/semver.js, tests/presets.spec.js, tests/semver.spec.js, versionist.conf.js
Using Versionist is very manual. We require users to manually specify the
range of commits to be parsed with the `--from` and `--to` CLI arguments.
Since the addition of the `getChangelogDocumentedVersions` hook, we can use
the information returned by that function to automatically infer these
values.
The CLI doesn't have the `--from`/`--to` options anymore and instead:
- Defaults `--to` to `HEAD`.
- Defaults `--from` to the greater version returned by
`getChangelogDocumentedVersions`.
Change-Type: major
Changelog-Entry: Automatically infer the appropriate git commit range.
=> feat: infer `--from` and `--to`

CHANGELOG.md
For simplicity purposes. We'll be extending presets to take arguments
shortly, which would allows to deal with this edge case with the
`addEntryToChangelog`'s `prepend` preset.
=> chore: remove CHANGELOG header

README.md, bin/cli.js
This function makes Versionist add the generated entry to the CHANGELOG
automatically, which is the default behaviour.
Instead, if the option is set to `false`, the generated entry is simply
printed to `stdout`, which is very useful for debugging purposes, or
while the user is working on its template.
Changelog-Entry: Add `editChangelog` option.
=> feat: add `editChangelog` option

lib/semver.js
`semver.compare` can be passed to `Array#sort()` directly, which greatly
simplifies our reducer function uses `semver.gt`.
=> refactor: use semver.compare to sort versions

README.md, bin/cli.js, lib/presets.js, package.json, tests/presets.spec.js, versionist.conf.js
- `updateVersion`
This option hook would be used to automatically increment the version in
the current project. It ships with a default `npm` preset which updates
`package.json`.
- `editVersion`
This option is used to control whether the project version will be edited
by using the `updateVersion` hook.
=> Add `updateVersion` and `editVersion` options

README.md
Recent commits introduced plenty features, like automatic `CHANGELOG`
and `package.json` editing.
The example from the `README.md` was updated to showcase this feature.
In order to make sure there are always enough changes to get something
generated, we added an `example` annotated tag and instruct the user to
`checkout` it.
=> docs: update README example to showcase new features

README.md, bin/cli.js, lib/presets.js, tests/presets.spec.js
This PR allows the user to make use of a preset with an optional object
notation that looks like this:
```
module.exports = {
...
addEntryToChangelog: {
preset: 'prepend',
optionSupportedByPrepend1: 'value',
optionSupportedByPrepend2: 'value'
}
...
}
```
The options are then passed as the first argument to the preset.
Changelog-Entry: Add support for preset options.
=> feat: add support for preset options

CHANGELOG.md, README.md, lib/presets.js, tests/presets.spec.js, versionist.conf.js
The CHANGELOG header was removed in 62c4da9 for simplicity purposes,
given we didn't have an easy way to deal with it on
`addEntryToChangelog` `prepend` preset.
This PR implements a `fromLine` option to the `prepend` preset, which as
the name implies, causes the prepending to happen from a certain line.
Now that we have this feature, we restore the original CHANGELOG header
and make use of `fromLine` in our `versionist.conf.js`.
Changelog-Entry: Implement `fromLine` option for `addEntryToChangelog`'s `prepend` preset.
=> feat: implement addEntryToChangelog `prepend` `fromLine` option

README.md, bin/cli.js
This project now has its own Gitter channel, where we'll point from the
README and from error messages.
See: https://gitter.im/resin-io/versionist
=> chore: point to new versionist gitter channel

bin/cli.js
This module mixes a lot of synchronous and asynchronous code. To make
sure every single exception is caught gets nicely displayed in the CLI
tool, we listen to the `uncaughtException` `process` event.
Changelog-Entry: Make sure every exception is nicely displayed.
=> fix: make sure every exception is nicely displayed

README.md, bin/cli.js, lib/versionist.js, tests/versionist.spec.js
This hook is useful to perform more advanced manipulations to the data
that is passed to the template. Can be useful in certain situations.
Changelog-Entry: Add `transformTemplateData` option hook.
=> feat: add `transformTemplateData` option hook

bin/cli.js
The callbacks in this waterfall entry all yield a version. When omitting
the version, we call `callback` without parameters, therefore the next
waterfall entry passes the new callback as the first parameter, causing
a confusing error to be thrown.
In order to be consistent with other callback calls, we manually pass a
`null` version as the second argument.
Changelog-Entry: Fix uncaught exception if current version is omitted.
=> fix: uncaught exception if current version is omitted

README.md, bin/cli.js, lib/presets.js, lib/semver.js, lib/versionist.js, tests/presets.spec.js, tests/semver.spec.js, tests/versionist.spec.js
This hook can be declared to customise how a version is incremented
given an increment level. It can be handy in some edge cases, and
defaults to incrementing a version based on semver rules.
Changelog-Entry: Add `incrementVersion` option hook.
=> feat: add `incrementVersion` option hook

lib/presets.js, tests/presets.spec.js
Currently, the `.getChangelogDocumentedVersions()` `changelog-headers`
preset throws an `ENOENT` error if a CHANGELOG file doesn't yet exist.
This causes confusions for users configuring Versionist on their
projects right at the beginning.
A better behaviour is to yield an empty array.
Changelog-Entry: Don't throw ENOENT in `changelog-headers` preset if the changelog file doesn't exist.
=> fix: `changelog-headers` ENOENT when no changelog file

lib/presets.js, tests/presets.spec.js, tests/versionist.spec.js
Presets should take an option object as the first argument. Such object
is automatically partially applied by the CLI when reading the
configuration file.
=> minifix: invalid version when using `semver` `incrementVersion` preset

README.md, bin/cli.js
This option, which defaults to `0.0.1`, can be used to configure the
desired default initial version in case the
`getChangelogDocumentedVersions` hook doesn't find any version.
If the default version reference can't be found on git, then all commits
from the beginning of the project will be included in such version.
Changelog-Entry: Add `defaultInitialVersion` option.
=> feat: add `defaultInitialVersion` option

.gitignore, package.json, tests/cli/cases/no-changelog.js, tests/cli/run.js, tests/cli/utils.js
This test suite creates real repositories with real commits and performs
actions on them using the Versionist CLI. This approach will allow us to
run tests on the CLI code, and make sure certain scenarious are free
from regressions
The e2e test suite will run with `npm test` automatically.
=> test: create a basic CLI end to end test suite

README.md
Making sense about how all the available options play together to
perform their job is hard to grok for a beginner. This documentation
block attempts to ease that by explaining in detail how/when Versionist
uses all the available options.
=> doc: document how all options fit together

.travis.yml, appveyor.yml, tests/cli/run.js, tests/cli/utils.js
Turns out non-zero exit codes are swallowed by `shelljs.exec`.
Making sure that a non-zero exit code from the CLI test cases halts the
CI builds reveals that the CI services require us to configure `git`
before being able to use it directly to perform a commit.
We also needed to save the git commit message to a temporary file and
re-use it with `-F` on `git commit` given that Windows gets confused by
line breaks in `-m`.
See: http://stackoverflow.com/a/20438380/1641422
=> minifix: make sure CLI tests exit with exit code 1 on failure

bin/cli.js, lib/versionist.js, tests/cli/cases/no-parse-footer-tags.js
The `parseFooterTags` config value was not propagated to
`gitLog.parseGitLogYAMLOutput()` via `versionist.readCommitHistory()`.
Changelog-Entry: Fix `parseFooterTags` not taking effect.
=> fix: `parseFooterTags` not taking effect

tests/cli/cases/no-parse-footer-tags.js
The linter complained that the `commit` parameter was not used in the
function body.
=> style: fix lint warning in `no-parse-footer-tags.js` test case

bin/cli.js, tests/cli/cases/idempotence.js
If we repeatedly call Versionist from the beginning of a project, all
the commits so far will be added over and over again.
The reason for this is that we default the start commit for
`versionist.readCommitHistory()` to `null` if a reference is not found,
independently on if it corresponds to the default initial version or
not.
To solve this issue, we only default the start commit to `null` if no
documented version was found on the repository.
Changelog-Entry: Reject non-existent git references if there are documented versions.
=> fix: reject non-existent git refs if there are documented versions

bin/cli.js, lib/cli/configuration.js, tests/cli-configuration.spec.js
The CLI configuration file loading/parsing logic is moved to
`lib/cli/configuration.js`. Moving this logic to a different file allows
this functionality to be unit-tested more easily.
=> refactor: extract CLI configuration logic to a new module

bin/cli.js, tests/cli/cases/config-file.js, tests/cli/utils.js
Due to the way `yargs` operates, a named option cannot be used
as an object to pass back a new set of options (in this case
the loaded configuration), as the key on `argv` essentially already
exists.
To mitigate this, the returned object is renamed `configuration` and
this is used in place of `config` for all further operations.
Connects to #46.
Changelog-Entry: Ensure a specified config file is parsed correctly.
=> fix: ensure a specified config file is parsed correctly

package.json
So that versionist can be run on itself, without needing to be installed
globally.
Fixes #64
=> Add a `versionist` script to `package.json`

versionist.conf.js
Connects to #80 and #76
There are two ways to add the `change-type: none` flag, internally we map the 3 levels to the semver lib so we could add a fourth level 'none' and then drop it before passing to semver but this was a far simpler approach.
=> Make change-type insensitive & add change-type none

lib/presets.js, tests/cli/cases/nested-changelog.js
Remove extra "v" appearing before version in nested changelogs
Signed-off-by: Giovanni Garufi <giovanni@resin.io>
=> lib/presets: fix nested changelog

src/tags.ts, tests/tags.spec.js
Currently commits that result from running `git cherry-pick -x COMMIT`
are not allowed by versionist.
Connects-to: https://github.com/balena-io/versionist/issues/133
Signed-off-by: Robert Günzler <robertg@balena.io>
=> Do not reject cherry-picked commits

src/versionist.ts, tests/cli/cases/empty-parsable-changelog.js, tests/cli/cases/parsable-changelog.js
Also do not throw an error if CHANGELOG.yml file is empty but just treat
it as an empty array
Fixes: balena-io/balena-versionist#28
=> Create parsable changelog if .versionbot folder is present

src/presets.js, tests/presets.spec.js
Added subject, which extracts increment level from the prefix in the
commit subject
Added changeTypeOrSubject which tries to extract the increment from the
change type at first, and if that fails tries to extract it from the
subject instead
Fixes: #164 
=> Add getIncrementLevelFromCommit options

src/presets.js
`octokit.authenticate` was removed in v17 as part of the
> All deprecated methods and options have been removed. Upgrade to the latest 16.x.x version and address all deprecation messages for an easy upgrade.
message, the problem is since we only try to authenticate for nested changelogs it was very rare for the deprecation notice to be printed. This should fix that
=> Fix authentication

src/presets.js
Previously the order of nested changelogs was dependent on a race
condition, now it will always be consistent regardless of how long
fetching the nested entries takes
=> Guarantee the order of nested changelogs

src/presets.js, tests/presets.spec.js
Make commit footer change-type checks case insensitive, to remove contribution friction.
=> Make change-type checks case insensitive

src/semver.ts, tests/presets.spec.js, tests/versionist.spec.js
Continuation of #184, updated `semserver` validation and added a couple of tests.
=> Update semserver to do a case-insensitive change-type check

src/presets.js, tests/presets.spec.js, tests/versionist.spec.js
Subject change-type check was very loose before, now the subject needs to start with case-insensitive major|minor|patch, followed by a colon in order for the type to be parsed.
=> Make subject change-type check stricter

scripts/generate-changelog.sh
yq versions before 3.4.0 output the version information to stderr
https://github.com/mikefarah/yq/issues/537
This patch redirects stderr to stdout.
Signed-off-by: Alex Gonzalez <alexg@balena.io>
=> generate-changelog: Fix yq version check

src/presets.js, tests/presets.spec.js
Updates the nested `packages[""].version` in the same way as the root version. I don't know if this key will exist in following `lockfileVersion`s, there is an explicit check for it. Also not sure under what node version this code will be run (need to update a couple of other packages that have this dependency) so check is not using the optional chaining operator (?.).
=> Update nested package-lock version

src/github.ts, src/presets.js
GitHub get content API does not allow pulling files bigger than 1MB, switching to using trees and blob. 
=> Get changelog.yml blob

src/presets.js, tests/cli/cases/nested-changelog.js
While using Changelogs generated by versionbot through a parser. There occured an issue of missing blockquotes with the following error message: 
```
SyntaxError: /home/vipulgupta2048/work/docusaurous/docs/CHANGELOG.md: Expected corresponding JSX closing tag for <blockquote>. (75:0)
73 | <li parentName="ul">{`Upgrade to postgres 13 `}{`[Pagan Gazzard]`}</li>
74 | </ul>
> 75 | </details>
| ^
76 | </blockquote>
77 | <details>
78 | <summary> chore(deps): updated open-balena-s3 to 2.13.3 [Bart Versluijs] </summary>
client (webpack 5.74.0) compiled with 1 error
```
This PR is aimed towards fixing all Changelogs having this issue. 
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
=> patch: Resolve missing blockquote

src/presets.js, tests/presets.spec.js
Updates the nested packages[""].version in the same way as the root version. We already do this for package-lock.json
Relates-to: #199
=> Update nested npm-shrinkwrap version

scripts/generate-changelog.sh
By default the `curl` command will not return an error reponse for non 2xx HTTP response. This change adds the [-f flag](https://curl.se/docs/manpage.html#-f) to the pull request query to allow it to fail if authorization fails instead of looping forever.
=> Fail changelog generation if not authorized

package-lock.json, package.json, src/presets.js, tests/presets.spec.js
[Cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) allow to have multiple crates in the same repository, to extend a library via optional features or helper packages. This PR adds support for a simple case of cargo workspaces where the same version is inherited by all sub-crates, allowing the workspace version and its members to be updated through this tool.
Add supports for a particular use case of [Cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) where the version is managed via `[workspace.package]` and all the members have the version configured as `version = {workspace = true}`
=> Add support for cargo workspaces
