product-os/versionist

README.md

style: make sure all README paragraphs are wrapped

---

README.md

style: fix README typo

---

lib/presets.js
lib/tags.js

Signed-off-by: Juan Cruz Viotti <jviotti@openmailbox.org>

chore: fix lint warnings introduced in new ESLint versions

---

README.md
lib/git-log.js
tests/git-log.spec.js
tests/utils.js
tests/versionist.spec.js

The hash of the commit is retrieved by git, and parsed from the yaml, then passed through as normal to the configuration file.
Connects-To: #50

Add the passing of commit hash to the config file.

---

versionist.conf.js

…ry and not the CWD.
Connects to #53.
change-type: patch

Ensure that referencing lodash occurs via the versionist base directory and not the CWD

---

versionist.conf.js

Connects to #56.
change-type: patch

Remove `lodash` completely, removing dependencies on non-standard library

---

bin/cli.js
lib/cli/configuration.js
tests/cli-configuration.spec.js

Connects to #58.
change-type: minor

Default to internal versionist.conf.js if none is passed (#58)

---

bin/cli.js
package.json

connects to #42
change-type: patch

Only output stack trace if DEBUG=versionist (#42)

---

bin/cli.js
tests/cli/cases/missing-changetype-commits.js
tests/cli/utils.js

Show nice error message instead of crashing if version incrementing commits are missing

---

README.md
lib/presets.js

Connects-to: #99
---- Autogenerated Waffleboard Connection: Connects to #99

Python __init__ file support

---

bin/cli.js
lib/cli/configuration.js
lib/presets.js
lib/semver.js
lib/versionist.js
package.json
tests/versionist.spec.js

Signed-off-by: Giovanni Garufi <giovanni@resin.io>

nested-changelogs: Add support for nested changelogs

---

lib/presets.js

Signed-off-by: Giovanni Garufi <giovanni@resin.io>

lib/presets: Accept multiple upstreams in nested-changelogs

---

lib/presets.js
tests/cli/cases/nested-changelog.js

Signed-off-by: Giovanni Garufi <giovanni@resin.io>

presets: Remove extra semicolon from version

---

lib/presets.js
package-lock.json
tests/presets.spec.js

Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

Check package-lock.json and npm-shrinkwrap.json

---

lib/presets.js
tests/presets.spec.js

Throw if all commits have been filtered out in changelog-entry preset

---

README.md

Signed-off-by: Matthew McGinn <mamcgi@gmail.com>

Update README.md resin references to balena

---

lib/presets.js

Signed-off-by: Will Boyce \<will@balena.io\>

do not require "Update" to be title-case in commit body

---

lib/presets.js

Add support for multiple upstream updates in a single commit

---

src/presets.js
tests/presets.spec.js

This will attempt an npm/cargo/python/generic update in parallel
ignoring any errors.

Add mixed preset for updateVersion

---

.versionbot/CHANGELOG.yml

Signed-off-by: Will Boyce \<will@balena.io\>

versionbot: add structured CHANGELOG.yml

---

scripts/generate-changelog.sh

Signed-off-by: Will Boyce \<will@balena.io\>

add script for generating structured changelogs from git history

---

README.md
bin/cli.js
package.json

Signed-off-by: Matthew McGinn <matthew@balena.io>

meta: update resin references to balena, remove dead gitter

---

src/presets.js
tests/cli/cases/generic-no-version.js
tests/presets.spec.js

Create VERSION file if not preset

---

bin/cli.js
src/cli/configuration.js
src/presets.js
src/versionist.ts
tests/cli/cases/parsable-changelog.js

Move editing of CHANGELOG.yml after dry checks

---

src/cli/configuration.js
src/presets.js
tests/presets.spec.js

Fix presets to have proper casing

---

src/presets.js
tests/presets.spec.js

Extend has-changetype so subject changes are also considered

---

bin/cli.js

Remove issues call to action

---

src/presets.js

Fix calling removed function

---

src/presets.js

Fix a call to octokit that was not updated to the new verison

---

bin/cli.js
src/cli/configuration.js
src/presets.js
tests/presets.spec.js

If `balena.yml` exists on a repo, update its version.

Update balena.yml version

---

src/presets.js
tests/presets.spec.js

Add versionist.versionPublishedAt field to package.json

---

package-lock.json
package.json
src/semver.ts

Signed-off-by: Kyle Harding <kyle@balena.io>

Replace resin-semver 1.6.0 with balena-semver 2.3.0

---

README.md
bin/cli.js
src/versionist.ts
tests/cli/cases/changelog-title.js
tests/cli/cases/empty-parsable-changelog.js

versionist can accept a title (--title, -t). It won't do anything with it by default, but it is accessible in the template.

Add changelog title support

---

src/presets.js

The nested changelog support currently needs to be provided with the
version range on the commit body, similarly to:
Update <submodule> from <initialVersion> to <targetVersion>
This is cumbersome and does not work well with tools that automatically
update submodule dependencies like renovatebot.
This commit keeps the legacy behaviour but will extract the version range
from git metadata when not provided. This new behaviour can be used by
specifyng a commit body similar to:
Update <submodule>
Signed-off-by: Alex Gonzalez <alexg@balena.io>

Deduce submodule update versions automatically

---

scripts/generate-changelog.sh

Fix generate-changelog.sh script when there are no versioned PRs

---

scripts/generate-changelog.sh

Update expressions yq v4

---

scripts/generate-changelog.sh

Fix changelog generation to handle special .github repo names

---

scripts/generate-changelog.sh

Exclude document breaks when merging changelog files

---

package-lock.json
package.json
repo.yml
tests/presets.spec.js

See: https://balena.zulipchat.com/#narrow/channel/346007-balena-io.2FbalenaCloud/topic/balenaMachine.20repo.20stuck.20on.20v14.2E1.2E1000/near/503081215
Change-type: major

Balena semver 3
